name: grid2op-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - keras
  - pip:
    - grid2op[challenge]
    - l2rpn-baselines
    - jyquickhelper
    - numpy
    - numba
    - keras
    - seaborn
    - plotly
